apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-frontend
  labels:
    app: {{ .Values.name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-frontend
    spec:
      containers:
        - name: {{ .Values.name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-frontend
  labels:
    app: {{ .Values.name }}-frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
  selector:
    app: {{ .Values.name }}-frontend
