apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-headlines-frontend
  labels:
    app: world-headlines-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world-headlines-frontend
  template:
    metadata:
      labels:
        app: world-headlines-frontend
    spec:
      containers:
        - name: world-headlines-frontend
          image: harbor.rst0070.com/world-headlines/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: world-headlines-frontend
  labels:
    app: world-headlines-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: world-headlines-frontend
