apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: world-headlines-gnews-crawling
spec:
  schedule: "0 * * * *"
  serviceAccountName: argo-workflow
  workflowSpec:
    entrypoint: gnews-crawling
    templates:
    - name: gnews-crawling
      dag:
        tasks:
        - name: crawl-gnews
          template: crawl-gnews

    - name: crawl-gnews
      container:
        image: harbor.rst0070.com/world-headlines/gnews-crawling:latest
        imagePullPolicy: Always
        env:
          - name: INFISICAL_TOKEN
            valueFrom:
              secretKeyRef:
                name: world-headlines-infisical
                key: INFISICAL_TOKEN
          - name: INFISICAL_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: world-headlines-infisical
                key: INFISICAL_PROJECT_ID
          - name: INFISICAL_HOST
            valueFrom:
              secretKeyRef:
                name: world-headlines-infisical
                key: INFISICAL_HOST
          - name: INFISICAL_ENVIRONMENT
            value: prod
