FROM apache/airflow:latest-python3.11

USER root
# other things
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git && \
    apt-get install firefox-esr -y

USER airflow
COPY requirements.txt /
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt