include:
  - compose.airflow.yaml

services:

  database:
    container_name: wh-postgres
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ../../sql/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  backend:
    container_name: wh-backend
    build: ../../backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - JDBC_DB_CONN_STR=${JDBC_DB_CONN_STR}
      - JDBC_DB_USERNAME=${JDBC_DB_USERNAME}
      - JDBC_DB_PASSWORD=${JDBC_DB_PASSWORD}
    ports:
      - "443:443"