import type { Metadata } from "next";
import localFont from "next/font/local";
import GlobalData from "../app.data";
import "./styles.css";
import { DetailedHTMLProps } from "react";
import { Headline } from "../models";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCountryButtons(): Promise<DetailedHTMLProps[]>{
  let buttons = []
  return new Promise((res, rej)=>{
    GlobalData.country_codes.forEach(async (code, i, a)=>{
      let headline:Headline = await GlobalData.headline_map.get(code)
      //console.log(headline)
      let element:DetailedHTMLProps = <li><a href={'/'+code}>{headline.country}</a></li>
      buttons.push(element)
      if(i == a.length-1){
        res(buttons)
      }
    })
  })
  
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let country_list_link = getCountryButtons()
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
            <h1>World Headlines</h1>
            <nav>
                <ul>
                  {country_list_link}
                </ul>
            </nav>
        </header>
        <main>
            {children}
        </main>
      </body>
    </html>
  );
}
